"use client";

import Link from "next/link";
import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import { fadeUp, heroStagger, stagger, scaleIn, tapScale, editorial } from "@/lib/motion";
import { ScrollReveal } from "@/components/motion/ScrollReveal";

// --- Hero Section ---
function HeroSection() {
  return (
    <section className="mx-auto max-w-[1200px] px-4 pt-20 pb-16 md:px-8 md:pt-32 md:pb-24">
      <motion.div
        className="mx-auto max-w-3xl text-center"
        variants={heroStagger}
        initial="hidden"
        animate="visible"
      >
        <motion.p
          variants={fadeUp}
          className="text-caption mb-6 uppercase tracking-[0.2em] text-muted"
        >
          Philosophical Coaching
        </motion.p>
        <motion.h1 variants={fadeUp} className="text-hero mb-6 text-ink">
          Ancient Wisdom.{" "}
          <span className="italic text-accent">Modern Clarity.</span>
        </motion.h1>
        <motion.p
          variants={fadeUp}
          className="text-body mx-auto mb-10 max-w-xl text-muted leading-relaxed text-lg"
        >
          Navigate daily anxiety, big decisions, and emotional struggles with
          guidance rooted in centuries of philosophical wisdom — delivered
          through a beautiful, adaptive experience.
        </motion.p>
        <motion.div
          variants={fadeUp}
          className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
        >
          <Link
            href="/auth/signup"
            className="inline-block rounded-md bg-accent px-8 py-3 text-sm font-semibold uppercase tracking-[0.05em] text-paper-light transition-colors duration-150 hover:bg-accent-hover"
          >
            Begin Your Journey
          </Link>
          <Link
            href="/explore"
            className="inline-block rounded-md border-2 border-ink px-8 py-3 text-sm font-semibold uppercase tracking-[0.05em] text-ink transition-colors duration-150 hover:bg-ink hover:text-paper"
          >
            Explore Schools
          </Link>
        </motion.div>

        {/* Scroll indicator */}
        <motion.div
          className="mt-16 flex justify-center text-muted"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.2, duration: 0.6 }}
        >
          <motion.svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            animate={{ y: [0, 6, 0] }}
            transition={{ repeat: Infinity, duration: 2, ease: "easeInOut" }}
          >
            <path d="M6 9l6 6 6-6" />
          </motion.svg>
        </motion.div>
      </motion.div>
    </section>
  );
}

// --- Widget Type Showcase ---
function WidgetShowcase() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, amount: 0.2 });

  const types = [
    {
      label: "01",
      title: "Read & Reflect",
      subtitle: "Display Widgets",
      description:
        "Curated Stoic wisdom, breathing exercises, and philosophical dilemmas. Fresh content generated by AI, tailored to your emotional state.",
      mockup: (
        <div className="rounded-lg border border-muted-light bg-paper-light p-4">
          <div className="h-1.5 w-12 rounded bg-accent/30 mb-3" />
          <div className="border-l-2 border-accent pl-3">
            <p className="font-display text-sm italic text-ink leading-relaxed">
              &ldquo;The happiness of your life depends upon the quality of your
              thoughts.&rdquo;
            </p>
          </div>
          <div className="mt-3 flex items-center gap-2">
            <div className="h-1 w-1 rounded-full bg-muted" />
            <span className="font-mono text-[0.6rem] text-muted">
              Marcus Aurelius
            </span>
          </div>
          <div className="mt-3 rounded bg-paper p-2.5">
            <div className="h-1.5 w-full rounded bg-muted-light/60 mb-1.5" />
            <div className="h-1.5 w-3/4 rounded bg-muted-light/40" />
          </div>
        </div>
      ),
    },
    {
      label: "02",
      title: "Practice & Save",
      subtitle: "Interactive Widgets",
      description:
        "Journaling prompts, gratitude lists, and cognitive reframes. Your responses are saved to build a personal philosophical journal over time.",
      mockup: (
        <div className="rounded-lg border border-muted-light bg-paper-light p-4">
          <div className="h-1.5 w-16 rounded bg-slate/30 mb-3" />
          <p className="font-display text-xs text-ink mb-3">
            What are you grateful for today?
          </p>
          <div className="space-y-2">
            {["Morning coffee", "A good conversation", ""].map((text, i) => (
              <div
                key={i}
                className="flex items-center gap-2 rounded border border-muted-light/60 bg-paper px-3 py-1.5"
              >
                <span className="font-mono text-[0.6rem] text-sage">
                  {i + 1}.
                </span>
                <span className="text-xs text-ink/60">
                  {text || "Write something..."}
                </span>
              </div>
            ))}
          </div>
          <div className="mt-3 flex justify-end">
            <div className="rounded bg-accent/10 px-3 py-1 text-[0.6rem] font-mono text-accent uppercase">
              Save
            </div>
          </div>
        </div>
      ),
    },
    {
      label: "03",
      title: "Talk to Your Coach",
      subtitle: "Chat Trigger Widgets",
      description:
        "Tap how you feel or choose a conversation starter. Instantly opens a dialogue with your Daily Sage — no blank page anxiety.",
      mockup: (
        <div className="rounded-lg border border-muted-light bg-paper-light p-4">
          <div className="h-1.5 w-20 rounded bg-warm/30 mb-3" />
          <p className="text-xs text-muted mb-3">How are you feeling?</p>
          <div className="grid grid-cols-5 gap-1.5">
            {["😌", "😊", "😤", "😰", "😔"].map((emoji, i) => (
              <div
                key={i}
                className={`flex items-center justify-center rounded-lg border p-2 text-sm ${
                  i === 0
                    ? "border-sage bg-sage/10"
                    : "border-muted-light/60 bg-paper"
                }`}
              >
                {emoji}
              </div>
            ))}
          </div>
          <div className="mt-3 rounded border border-sage/30 bg-sage/5 px-3 py-1.5">
            <span className="text-[0.6rem] text-sage">
              &rarr; &ldquo;I&apos;m feeling calm right now&rdquo;
            </span>
          </div>
        </div>
      ),
    },
  ];

  return (
    <section
      ref={ref}
      className="mx-auto max-w-[1200px] px-4 py-20 md:px-8 md:py-28"
    >
      <ScrollReveal>
        <h2 className="text-h2 mb-4 text-center text-ink">
          Not Just a Chatbot.
          <br />A Living Dashboard.
        </h2>
        <p className="text-body-sm mx-auto mb-4 max-w-2xl text-center text-muted">
          Most apps give you a chatbot <em>or</em> exercises.
          This gives you both — an AI coach that builds a personal dashboard
          of interactive tools, customized to your emotional state.
        </p>
        <p className="text-body-sm mx-auto mb-16 max-w-lg text-center font-medium text-ink">
          Three widget types, one unified experience.
        </p>
      </ScrollReveal>

      <motion.div
        className="grid gap-8 md:grid-cols-3"
        variants={stagger}
        initial="hidden"
        animate={inView ? "visible" : "hidden"}
      >
        {types.map((type) => (
          <motion.div
            key={type.label}
            variants={fadeUp}
            className="group"
          >
            <div className="mb-4">{type.mockup}</div>
            <span className="font-mono text-xs font-medium text-accent">
              {type.label}
            </span>
            <h3 className="text-h3 mt-1 mb-1 text-ink">{type.title}</h3>
            <p className="text-caption uppercase tracking-wider text-muted mb-2">
              {type.subtitle}
            </p>
            <p className="text-body-sm text-muted leading-relaxed">
              {type.description}
            </p>
          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}

// --- Dashboard Preview Mockup ---
function DashboardPreview() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, amount: 0.15 });

  const mockWidgets = [
    { type: "quote", h: "h-28", color: "accent" },
    { type: "feeling", h: "h-24", color: "warm" },
    { type: "breathing", h: "h-32", color: "sage" },
    { type: "gratitude", h: "h-36", color: "slate" },
  ];

  return (
    <section
      ref={ref}
      className="border-y border-muted-light bg-paper-light"
    >
      <div className="mx-auto max-w-[1200px] px-4 py-20 md:px-8 md:py-28">
        <ScrollReveal>
          <h2 className="text-h2 mb-4 text-center text-ink">
            Your Dashboard, Your Way
          </h2>
          <p className="text-body-sm mx-auto mb-16 max-w-lg text-center text-muted">
            The AI coach reads your mood and builds a personalized dashboard.
            Drag to rearrange, pin favorites, or ask for something new.
          </p>
        </ScrollReveal>

        {/* Browser chrome mockup */}
        <motion.div
          className="mx-auto max-w-4xl overflow-hidden rounded-xl border border-muted-light bg-paper shadow-lg"
          initial={{ opacity: 0, y: 40 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ ...editorial.slow, delay: 0.2 }}
        >
          {/* Chrome bar */}
          <div className="flex items-center gap-2 border-b border-muted-light bg-paper-light px-4 py-2.5">
            <div className="flex gap-1.5">
              <div className="h-2.5 w-2.5 rounded-full bg-muted-light" />
              <div className="h-2.5 w-2.5 rounded-full bg-muted-light" />
              <div className="h-2.5 w-2.5 rounded-full bg-muted-light" />
            </div>
            <div className="ml-4 h-5 w-56 rounded-sm bg-muted-light/40" />
          </div>

          {/* Dashboard + chat layout */}
          <div className="flex min-h-[320px]">
            {/* Widget grid area */}
            <div className="flex-1 p-5">
              <div className="mb-4 flex items-end justify-between">
                <div>
                  <div className="h-2 w-20 rounded bg-muted-light/50 mb-1.5" />
                  <div className="h-4 w-40 rounded bg-ink/15" />
                </div>
              </div>

              <motion.div
                className="grid grid-cols-2 gap-3"
                variants={stagger}
                initial="hidden"
                animate={inView ? "visible" : "hidden"}
              >
                {mockWidgets.map((w, i) => (
                  <motion.div
                    key={i}
                    variants={fadeUp}
                    custom={i}
                    className={`rounded-lg border border-muted-light/60 bg-paper-light p-3 ${w.h}`}
                  >
                    <div className={`h-1.5 w-10 rounded bg-${w.color}/25 mb-2`} />
                    <div className="h-2.5 w-24 rounded bg-ink/10 mb-1.5" />
                    <div className="h-1.5 w-full rounded bg-muted-light/40 mb-1" />
                    <div className="h-1.5 w-3/4 rounded bg-muted-light/30" />
                  </motion.div>
                ))}
              </motion.div>
            </div>

            {/* Chat panel */}
            <motion.div
              className="hidden w-56 border-l border-muted-light bg-paper p-4 sm:block"
              initial={{ x: 60, opacity: 0 }}
              animate={inView ? { x: 0, opacity: 1 } : {}}
              transition={{ ...editorial.enter, delay: 1.0 }}
            >
              <div className="h-1.5 w-16 rounded bg-muted-light/50 mb-4" />

              {/* Mock messages */}
              <div className="space-y-3">
                <div className="rounded bg-paper-light p-2">
                  <div className="h-1 w-8 rounded bg-muted-light mb-1.5" />
                  <div className="h-1.5 w-full rounded bg-ink/10 mb-1" />
                  <div className="h-1.5 w-3/4 rounded bg-ink/10" />
                </div>
                <div className="border-l-2 border-accent pl-2">
                  <div className="h-1 w-12 rounded bg-muted-light mb-1.5" />
                  <div className="h-1.5 w-full rounded bg-ink/8 mb-1" />
                  <div className="h-1.5 w-5/6 rounded bg-ink/8" />
                </div>

                {/* Mock widget in chat */}
                <motion.div
                  className="rounded-lg border border-muted-light bg-paper-light p-2"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={inView ? { opacity: 1, scale: 1 } : {}}
                  transition={{ ...editorial.enter, delay: 1.6 }}
                >
                  <div className="h-1 w-8 rounded bg-accent/30 mb-1.5" />
                  <div className="h-1.5 w-full rounded bg-ink/8 mb-1" />
                  <div className="h-1.5 w-2/3 rounded bg-ink/8" />
                  <div className="mt-2 h-4 w-20 rounded bg-accent/10" />
                </motion.div>
              </div>

              {/* Input bar */}
              <div className="mt-4 flex gap-1.5">
                <div className="flex-1 h-6 rounded border border-muted-light/60 bg-paper-light" />
                <div className="h-6 w-6 rounded bg-accent/15" />
              </div>
            </motion.div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

// --- Pull Quote ---
function PullQuote() {
  return (
    <section className="mx-auto max-w-[1200px] px-4 py-20 md:px-8 md:py-28">
      <ScrollReveal>
        <blockquote className="mx-auto max-w-2xl text-center">
          <p className="text-quote text-ink">
            &ldquo;We suffer more often in imagination than in reality.&rdquo;
          </p>
          <footer className="mt-6">
            <cite className="text-body-sm font-medium not-italic text-muted">
              — Seneca,{" "}
              <span className="font-mono text-xs">Letters to Lucilius</span>
            </cite>
          </footer>
        </blockquote>
      </ScrollReveal>
    </section>
  );
}

// --- How It Works (flow) ---
function HowItWorks() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, amount: 0.2 });

  const steps = [
    {
      num: "1",
      title: "Tell us how you feel",
      desc: "Place a pin on the mood canvas — no labels, no checkboxes. Just where you are right now.",
    },
    {
      num: "2",
      title: "AI builds your dashboard",
      desc: "Claude analyzes your emotional state and creates a personalized set of widgets: quotes, exercises, and conversation starters.",
    },
    {
      num: "3",
      title: "Practice & grow",
      desc: "Complete exercises, save reflections, and chat with your Daily Sage. Your philosophical journey builds over time.",
    },
  ];

  return (
    <section
      ref={ref}
      className="border-y border-muted-light bg-paper-light"
    >
      <div className="mx-auto max-w-[1200px] px-4 py-20 md:px-8 md:py-28">
        <ScrollReveal>
          <h2 className="text-h2 mb-4 text-center text-ink">
            30 Seconds to Start
          </h2>
          <p className="text-body-sm mx-auto mb-16 max-w-lg text-center text-muted">
            No sign-up essays. No personality quizzes. Just a mood check-in and
            you&apos;re in.
          </p>
        </ScrollReveal>

        <motion.div
          className="grid gap-8 md:grid-cols-3"
          variants={stagger}
          initial="hidden"
          animate={inView ? "visible" : "hidden"}
        >
          {steps.map((step) => (
            <motion.div
              key={step.num}
              variants={fadeUp}
              className="text-center"
            >
              <span className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-ink font-mono text-sm font-semibold text-ink">
                {step.num}
              </span>
              <h3 className="text-h3 mt-4 mb-2 text-ink">{step.title}</h3>
              <p className="text-body-sm text-muted leading-relaxed">
                {step.desc}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

// --- Built With Section ---
function BuiltWith() {
  const techs = [
    "Next.js 15",
    "Anthropic Claude",
    "Supabase",
    "AI SDK",
    "Tailwind CSS",
    "Framer Motion",
  ];

  return (
    <section className="mx-auto max-w-[1200px] px-4 py-20 md:px-8 md:py-28">
      <ScrollReveal>
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-caption mb-4 uppercase tracking-[0.2em] text-muted">
            Built for the Claude Code Hackathon
          </p>
          <h2 className="text-h2 mb-4 text-ink">Powered by Claude</h2>
          <p className="text-body-sm mx-auto mb-8 max-w-lg text-muted leading-relaxed">
            Every coaching response, every widget, every personalized dashboard
            is generated in real-time by Anthropic&apos;s Claude. The AI doesn&apos;t
            just chat — it builds the entire experience around you.
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            {techs.map((tech) => (
              <span
                key={tech}
                className="rounded-full border border-muted-light bg-paper-light px-4 py-1.5 font-mono text-xs text-muted"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>
      </ScrollReveal>
    </section>
  );
}

// --- Final CTA ---
function FinalCTA() {
  return (
    <section className="border-t border-muted-light bg-paper-light">
      <div className="mx-auto max-w-[1200px] px-4 py-20 text-center md:px-8 md:py-28">
        <ScrollReveal>
          <h2 className="text-h2 mb-4 text-ink">
            Ready to Think Differently?
          </h2>
          <p className="text-body-sm mx-auto mb-10 max-w-md text-muted">
            Start with a 30-second mood check-in. The philosophy will find you.
          </p>
          <motion.div whileHover={{ scale: 1.03 }} whileTap={tapScale}>
            <Link
              href="/auth/signup"
              className="inline-block rounded-md bg-accent px-8 py-3 text-sm font-semibold uppercase tracking-[0.05em] text-paper-light transition-colors duration-150 hover:bg-accent-hover"
            >
              Begin Your Journey
            </Link>
          </motion.div>
        </ScrollReveal>
      </div>
    </section>
  );
}

// --- Main Landing Content ---
export function LandingContent() {
  return (
    <>
      <HeroSection />

      {/* Editorial Divider */}
      <div className="mx-auto max-w-[1200px] px-4 md:px-8">
        <div className="editorial-divider">
          <span className="text-muted-light">&#9670;</span>
        </div>
      </div>

      <WidgetShowcase />
      <DashboardPreview />
      <PullQuote />
      <HowItWorks />
      <BuiltWith />
      <FinalCTA />
    </>
  );
}
