import type { PhilosophicalSchool, SchoolDefinition } from "@/types/philosophy";

export const philosophicalSchools: Record<PhilosophicalSchool, SchoolDefinition> = {
  stoicism: {
    name: "Stoicism",
    era: "Ancient Greece/Rome",
    core: "Focus on what you can control, accept what you cannot",
    bestFor: ["anxiety", "anger", "frustration", "uncertainty"],
    philosophers: ["Marcus Aurelius", "Epictetus", "Seneca"],
    color: "slate",
  },
  existentialism: {
    name: "Existentialism",
    era: "19th-20th Century",
    core: "Create your own meaning through authentic choices",
    bestFor: ["meaninglessness", "identity_crisis", "major_decisions"],
    philosophers: ["Kierkegaard", "Sartre", "Camus", "de Beauvoir"],
    color: "ink",
  },
  buddhism: {
    name: "Buddhist Philosophy",
    era: "Ancient India",
    core: "Suffering arises from attachment; mindfulness brings peace",
    bestFor: ["attachment", "grief", "restlessness", "overthinking"],
    philosophers: ["Siddhartha Gautama", "Thich Nhat Hanh", "Pema Chödrön"],
    color: "sage",
  },
  absurdism: {
    name: "Absurdism",
    era: "20th Century",
    core: "Embrace the absurd, find joy despite meaninglessness",
    bestFor: ["despair", "cynicism", "burnout", "dark_humor"],
    philosophers: ["Albert Camus", "Thomas Nagel"],
    color: "warm",
  },
  taoism: {
    name: "Taoism",
    era: "Ancient China",
    core: "Flow with nature, embrace simplicity and balance",
    bestFor: ["overwhelm", "perfectionism", "control_issues", "burnout"],
    philosophers: ["Laozi", "Zhuangzi"],
    color: "sage",
  },
  epicureanism: {
    name: "Epicureanism",
    era: "Ancient Greece",
    core: "Pursue simple pleasures, avoid unnecessary pain",
    bestFor: ["hedonic_treadmill", "materialism", "social_pressure"],
    philosophers: ["Epicurus", "Lucretius"],
    color: "warm",
  },
  pragmatism: {
    name: "Pragmatism",
    era: "19th-20th Century America",
    core: "Truth is what works; focus on practical outcomes",
    bestFor: ["analysis_paralysis", "perfectionism", "indecision"],
    philosophers: ["William James", "John Dewey", "Charles Peirce"],
    color: "slate",
  },
} as const;
